# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None
BASE = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['run_server.py'],
    pathex=[BASE],
    binaries=[
        (r'C:\Users\NO.1\AppData\Roaming\uv\python\cpython-3.11-windows-x86_64-none\DLLs\libssl-3-x64.dll', '.'),
        (r'C:\Users\NO.1\AppData\Roaming\uv\python\cpython-3.11-windows-x86_64-none\DLLs\libcrypto-3-x64.dll', '.'),
        (r'C:\Users\NO.1\AppData\Roaming\uv\python\cpython-3.11-windows-x86_64-none\DLLs\_ssl.pyd', '.'),
    ],
    datas=[
        ('app', 'app'),
        ('templates', 'templates'),
        ('frontend_dist', 'frontend_dist'),
        ('bin/poppler/Library/bin', 'bin/poppler/Library/bin'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.responses',
        'starlette.middleware',
        'starlette.middleware.cors',
        'pydantic',
        'pydantic_settings',
        'multipart',
        'python_multipart',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.chromium',
        'selenium.webdriver.chromium.webdriver',
        'selenium.webdriver.chromium.service',
        'selenium.webdriver.chromium.options',
        'selenium.webdriver.chromium.remote_connection',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.common.options',
        'selenium.webdriver.common.service',
        'selenium.webdriver.common.driver_finder',
        'selenium.webdriver.common.selenium_manager',
        'selenium.webdriver.remote',
        'selenium.webdriver.remote.webdriver',
        'selenium.webdriver.remote.remote_connection',
        'selenium.webdriver.remote.command',
        'selenium.webdriver.remote.errorhandler',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.support.wait',
        'pptx',
        'pptx.util',
        'pptx.enum.shapes',
        'fitz',
        'PIL',
        'PIL.Image',
        'PIL.ImageOps',
        'PIL.ImageEnhance',
        'numpy',
        'openpyxl',
        'pytesseract',
        'bs4',
        'requests',
        'websockets',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'httptools',
        'httptools.parser',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name='backend',
)
